# Generated by Django 6.0.3 on 2026-03-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת')),
                ('body', models.TextField(verbose_name='תוכן')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='נעוץ')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='תוקף')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Leave blank for all teams', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team', verbose_name='צוות')),
            ],
            options={
                'verbose_name': 'הודעה',
                'verbose_name_plural': 'הודעות',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='משימה')),
                ('description', models.TextField(blank=True, verbose_name='פירוט')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='משימה חוזרת')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team', verbose_name='צוות')),
            ],
            options={
                'verbose_name': 'משימה יומית',
                'verbose_name_plural': 'משימות יומיות',
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='שאלה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='בחירה מרובה')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='תוקף')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team', verbose_name='צוות')),
            ],
            options={
                'verbose_name': 'סקר',
                'verbose_name_plural': 'סקרים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='תשובה')),
                ('display_order', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='portal.poll')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='הערות')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='portal.dailytask')),
            ],
            options={
                'verbose_name': 'ביצוע משימה',
                'unique_together': {('task', 'completed_by')},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='portal.polloption')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הצבעה',
                'unique_together': {('option', 'voter')},
            },
        ),
    ]
