# Generated by Django 6.0.3 on 2026-03-30 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('category', models.CharField(choices=[('open', 'תקלה פתוחה'), ('escalation', 'הסלמה'), ('resolved', 'טופל'), ('heads_up', 'שים לב'), ('info', 'מידע כללי')], max_length=20, verbose_name='קטגוריה')),
                ('severity', models.CharField(choices=[('low', 'נמוך'), ('medium', 'בינוני'), ('high', 'גבוה')], default='medium', max_length=10, verbose_name='חומרה')),
                ('ticket_number', models.CharField(blank=True, max_length=50, verbose_name='מספר קריאה')),
                ('description', models.TextField(max_length=500, verbose_name='תיאור')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_notes', to=settings.AUTH_USER_MODEL, verbose_name='כותב')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_notes', to='core.team', verbose_name='צוות')),
            ],
            options={
                'verbose_name': 'הערת משמרת',
                'verbose_name_plural': 'הערות משמרת',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('scope', models.CharField(choices=[('team', 'צוות'), ('daily', 'יומי')], max_length=10, verbose_name='סוג')),
                ('summary_text', models.TextField(blank=True, verbose_name='סיכום AI')),
                ('notes_count', models.IntegerField(default=0, verbose_name='מספר הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compiled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compiled_summaries', to=settings.AUTH_USER_MODEL, verbose_name='סוכם ע״י')),
                ('team', models.ForeignKey(blank=True, help_text='Null for daily overview scope', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handoff_summaries', to='core.team', verbose_name='צוות')),
            ],
            options={
                'verbose_name': 'סיכום משמרת',
                'verbose_name_plural': 'סיכומי משמרות',
                'ordering': ['-date', 'team'],
                'unique_together': {('date', 'team', 'scope')},
            },
        ),
    ]
