# Generated by Django 6.0.3 on 2026-03-29 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='שנה')),
                ('month', models.IntegerField(verbose_name='חודש')),
                ('is_open_for_submissions', models.BooleanField(default=False, verbose_name='פתוח להגשת בקשות')),
                ('is_published', models.BooleanField(default=False, verbose_name='לוח פורסם')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_month_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'תצורת חודש',
                'verbose_name_plural': 'תצורות חודשים',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
                ('month_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.monthconfig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'verbose_name': 'שיבוץ',
                'verbose_name_plural': 'שיבוצים',
                'ordering': ['date', 'team'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_preferences', to=settings.AUTH_USER_MODEL)),
                ('month_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='scheduling.monthconfig')),
                ('preferred_teams', models.ManyToManyField(blank=True, related_name='preferred_by', to='core.team', verbose_name='צוותות מועדפים')),
            ],
            options={
                'verbose_name': 'בקשת משמרת',
                'verbose_name_plural': 'בקשות משמרות',
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TeamMonthCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_per_day', models.IntegerField(default=10, verbose_name='מקומות ליום')),
                ('month_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_capacities', to='scheduling.monthconfig')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
            options={
                'verbose_name': 'קיבולת צוות לחודש',
                'unique_together': {('month_config', 'team')},
            },
        ),
    ]
