# Generated by Django 6.0.3 on 2026-03-30 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='תאריך')),
                ('day_type', models.CharField(choices=[('off', 'יום חופש'), ('half', 'חצי יום'), ('reduced', 'קיבולת מופחתת')], max_length=10, verbose_name='סוג')),
                ('note', models.CharField(blank=True, help_text='סיבה או תיאור', max_length=300, verbose_name='הערה')),
                ('end_time', models.TimeField(blank=True, help_text='לחצי יום — שעת סיום העבודה (למשל 13:00)', null=True, verbose_name='שעת סיום')),
                ('capacity_percent', models.IntegerField(default=100, help_text='100 = רגיל, 50 = חצי מהמקומות, 0 = סגור', verbose_name='אחוז קיבולת')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_special_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'יום מיוחד',
                'verbose_name_plural': 'ימים מיוחדים',
                'ordering': ['date'],
            },
        ),
    ]
